# Generated by Django 5.1 on 2024-08-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avinyacontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Message', models.CharField(max_length=50)),
            ],
        ),
    ]
