# Generated by Django 5.1 on 2024-08-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avinyacollab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
                ('CompanyName', models.CharField(max_length=50)),
                ('Industry', models.CharField(max_length=50)),
                ('Comments', models.TextField()),
            ],
        ),
    ]
